// AUTO-GENERATED by scripts/generate-completions-index.ts - DO NOT EDIT
// Re-run `npm run build:completions` to regenerate

import mod0 from '../../../src/resources/webstorm/completions/webstorm.plugins.js';
import mod1 from '../../../src/resources/vscode/completions/vscode.extensions.js';
import mod2 from '../../../src/resources/snap/completions/snap.install.js';
import mod3 from '../../../src/resources/ruby/rbenv/completions/rbenv.rubyVersions.js';
import mod4 from '../../../src/resources/python/uv/completions/uv.tools.js';
import mod5 from '../../../src/resources/python/uv/completions/uv.pythonVersions.js';
import mod6 from '../../../src/resources/python/pyenv/completions/pyenv.pythonVersions.js';
import mod7 from '../../../src/resources/python/pip/completions/pip.install.js';
import mod8 from '../../../src/resources/ollama/completions/ollama.models.js';
import mod9 from '../../../src/resources/javascript/pnpm/completions/pnpm.globalEnvNodeVersion.js';
import mod10 from '../../../src/resources/javascript/nvm/completions/nvm.nodeVersions.js';
import mod11 from '../../../src/resources/javascript/npm/completions/npm.install.js';
import mod12 from '../../../src/resources/homebrew/completions/homebrew.formulae.js';
import mod13 from '../../../src/resources/homebrew/completions/homebrew.casks.js';
import mod14 from '../../../src/resources/cursor/completions/cursor.extensions.js';
import mod15 from '../../../src/resources/asdf/completions/asdf.plugins.js';
import mod16 from '../../../src/resources/asdf/completions/asdf-plugin.plugin.js';
import mod17 from '../../../src/resources/apt/completions/apt.install.js';

export interface CompletionModule {
  resourceType: string
  parameterPath: string
  fetch: () => Promise<string[]>
}

export const completionModules: CompletionModule[] = [
  { resourceType: 'webstorm', parameterPath: '/plugins', fetch: mod0 },
  { resourceType: 'vscode', parameterPath: '/extensions', fetch: mod1 },
  { resourceType: 'snap', parameterPath: '/install', fetch: mod2 },
  { resourceType: 'rbenv', parameterPath: '/rubyVersions', fetch: mod3 },
  { resourceType: 'uv', parameterPath: '/tools', fetch: mod4 },
  { resourceType: 'uv', parameterPath: '/pythonVersions', fetch: mod5 },
  { resourceType: 'pyenv', parameterPath: '/pythonVersions', fetch: mod6 },
  { resourceType: 'pip', parameterPath: '/install', fetch: mod7 },
  { resourceType: 'ollama', parameterPath: '/models', fetch: mod8 },
  { resourceType: 'pnpm', parameterPath: '/globalEnvNodeVersion', fetch: mod9 },
  { resourceType: 'nvm', parameterPath: '/nodeVersions', fetch: mod10 },
  { resourceType: 'npm', parameterPath: '/install', fetch: mod11 },
  { resourceType: 'homebrew', parameterPath: '/formulae', fetch: mod12 },
  { resourceType: 'homebrew', parameterPath: '/casks', fetch: mod13 },
  { resourceType: 'cursor', parameterPath: '/extensions', fetch: mod14 },
  { resourceType: 'asdf', parameterPath: '/plugins', fetch: mod15 },
  { resourceType: 'asdf-plugin', parameterPath: '/plugin', fetch: mod16 },
  { resourceType: 'apt', parameterPath: '/install', fetch: mod17 },
]
