// AUTO-GENERATED by scripts/generate-completions-index.ts - DO NOT EDIT
// Re-run `npm run build:completions` to regenerate

import mod0 from '../../../src/resources/xcodes/completions/xcodes.$.xcodeVersions.js';
import mod1 from '../../../src/resources/webstorm/completions/webstorm.$.plugins.js';
import mod2 from '../../../src/resources/vscode/completions/vscode.$.extensions.js';
import mod3 from '../../../src/resources/snap/completions/snap.$.install.js';
import mod4 from '../../../src/resources/ruby/rbenv/completions/rbenv.$.rubyVersions.js';
import mod5 from '../../../src/resources/python/uv/completions/uv.$.tools.js';
import mod6 from '../../../src/resources/python/uv/completions/uv.$.pythonVersions.js';
import mod7 from '../../../src/resources/python/pyenv/completions/pyenv.$.pythonVersions.js';
import mod8 from '../../../src/resources/python/pip/completions/pip.$.install.js';
import mod9 from '../../../src/resources/ollama/completions/ollama.$.models.js';
import mod10 from '../../../src/resources/jetbrains/rustrover/completions/rustrover.$.plugins.js';
import mod11 from '../../../src/resources/jetbrains/rubymine/completions/rubymine.$.plugins.js';
import mod12 from '../../../src/resources/jetbrains/rider/completions/rider.$.plugins.js';
import mod13 from '../../../src/resources/jetbrains/pycharm/completions/pycharm.$.plugins.js';
import mod14 from '../../../src/resources/jetbrains/phpstorm/completions/phpstorm.$.plugins.js';
import mod15 from '../../../src/resources/jetbrains/intellij-idea/completions/intellij-idea.$.plugins.js';
import mod16 from '../../../src/resources/jetbrains/goland/completions/goland.$.plugins.js';
import mod17 from '../../../src/resources/jetbrains/clion/completions/clion.$.plugins.js';
import mod18 from '../../../src/resources/javascript/pnpm/completions/pnpm.$.globalEnvNodeVersion.js';
import mod19 from '../../../src/resources/javascript/nvm/completions/nvm.$.nodeVersions.js';
import mod20 from '../../../src/resources/javascript/npm/completions/npm.$.install.js';
import mod21 from '../../../src/resources/ios/ios-simulator/completions/ios-simulators.$.simulators[x].runtime.js';
import mod22 from '../../../src/resources/ios/ios-simulator/completions/ios-simulators.$.simulators[x].deviceType.js';
import mod23 from '../../../src/resources/homebrew/completions/homebrew.$.formulae.js';
import mod24 from '../../../src/resources/homebrew/completions/homebrew.$.casks.js';
import mod25 from '../../../src/resources/cursor/completions/cursor.$.extensions.js';
import mod26 from '../../../src/resources/codex/completions/codex.$.config.model.js';
import mod27 from '../../../src/resources/asdf/completions/asdf.$.plugins.js';
import mod28 from '../../../src/resources/asdf/completions/asdf-plugin.$.plugin.js';
import mod29 from '../../../src/resources/apt/completions/apt.$.install.js';
import mod30 from '../../../src/resources/android/android-studios/completions/android-studio.$.version.js';
import mod31 from '../../../src/resources/android/android-cli/completions/android-cli.$.sdkPackages.js';
import mod32 from '../../../src/resources/android/android-cli/completions/android-cli.$.emulators.js';

export interface CompletionModule {
  resourceType: string
  parameterPath: string
  fetch: () => Promise<string[]>
}

export const completionModules: CompletionModule[] = [
  { resourceType: 'xcodes', parameterPath: '$.xcodeVersions', fetch: mod0 },
  { resourceType: 'webstorm', parameterPath: '$.plugins', fetch: mod1 },
  { resourceType: 'vscode', parameterPath: '$.extensions', fetch: mod2 },
  { resourceType: 'snap', parameterPath: '$.install', fetch: mod3 },
  { resourceType: 'rbenv', parameterPath: '$.rubyVersions', fetch: mod4 },
  { resourceType: 'uv', parameterPath: '$.tools', fetch: mod5 },
  { resourceType: 'uv', parameterPath: '$.pythonVersions', fetch: mod6 },
  { resourceType: 'pyenv', parameterPath: '$.pythonVersions', fetch: mod7 },
  { resourceType: 'pip', parameterPath: '$.install', fetch: mod8 },
  { resourceType: 'ollama', parameterPath: '$.models', fetch: mod9 },
  { resourceType: 'rustrover', parameterPath: '$.plugins', fetch: mod10 },
  { resourceType: 'rubymine', parameterPath: '$.plugins', fetch: mod11 },
  { resourceType: 'rider', parameterPath: '$.plugins', fetch: mod12 },
  { resourceType: 'pycharm', parameterPath: '$.plugins', fetch: mod13 },
  { resourceType: 'phpstorm', parameterPath: '$.plugins', fetch: mod14 },
  { resourceType: 'intellij-idea', parameterPath: '$.plugins', fetch: mod15 },
  { resourceType: 'goland', parameterPath: '$.plugins', fetch: mod16 },
  { resourceType: 'clion', parameterPath: '$.plugins', fetch: mod17 },
  { resourceType: 'pnpm', parameterPath: '$.globalEnvNodeVersion', fetch: mod18 },
  { resourceType: 'nvm', parameterPath: '$.nodeVersions', fetch: mod19 },
  { resourceType: 'npm', parameterPath: '$.install', fetch: mod20 },
  { resourceType: 'ios-simulators', parameterPath: '$.simulators[*].runtime', fetch: mod21 },
  { resourceType: 'ios-simulators', parameterPath: '$.simulators[*].deviceType', fetch: mod22 },
  { resourceType: 'homebrew', parameterPath: '$.formulae', fetch: mod23 },
  { resourceType: 'homebrew', parameterPath: '$.casks', fetch: mod24 },
  { resourceType: 'cursor', parameterPath: '$.extensions', fetch: mod25 },
  { resourceType: 'codex', parameterPath: '$.config.model', fetch: mod26 },
  { resourceType: 'asdf', parameterPath: '$.plugins', fetch: mod27 },
  { resourceType: 'asdf-plugin', parameterPath: '$.plugin', fetch: mod28 },
  { resourceType: 'apt', parameterPath: '$.install', fetch: mod29 },
  { resourceType: 'android-studio', parameterPath: '$.version', fetch: mod30 },
  { resourceType: 'android-cli', parameterPath: '$.sdkPackages', fetch: mod31 },
  { resourceType: 'android-cli', parameterPath: '$.emulators', fetch: mod32 },
]
