import { globSync } from 'glob'
import fs from 'node:fs'
import path from 'node:path'
import * as url from 'node:url'

const __dirname = path.dirname(url.fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '..')
const srcDir = path.resolve(repoRoot, 'src')
const outputFile = path.resolve(repoRoot, 'completions-cron', 'src', '__generated__', 'completions-index.ts')

const completionFiles = globSync('resources/**/completions/*.ts', {
  cwd: srcDir,
  posix: true,
})

const lines: string[] = [
  '// AUTO-GENERATED by scripts/generate-completions-index.ts - DO NOT EDIT',
  '// Re-run `npm run build:completions` to regenerate',
  '',
]

const modules = completionFiles.map((relPath, i) => {
  const filename = path.basename(relPath, '.ts')
  const dotIndex = filename.indexOf('.')
  if (dotIndex === -1) {
    throw new Error(
      `Completion file must be named <resource-type>.<parameter-name>.ts, got: ${filename}`
    )
  }
  const resourceType = filename.substring(0, dotIndex)
  const parameterPath = '/' + filename.substring(dotIndex + 1)

  // Path from completions-cron/src/__generated__/ back to plugin src/resources/
  const importPath = '../../../src/' + relPath.replace(/\.ts$/, '.js')
  const importName = `mod${i}`

  return { importName, importPath, resourceType, parameterPath }
})

for (const { importName, importPath } of modules) {
  lines.push(`import ${importName} from '${importPath}';`)
}

lines.push('')
lines.push('export interface CompletionModule {')
lines.push('  resourceType: string')
lines.push('  parameterPath: string')
lines.push('  fetch: () => Promise<string[]>')
lines.push('}')
lines.push('')
lines.push('export const completionModules: CompletionModule[] = [')
for (const { importName, resourceType, parameterPath } of modules) {
  lines.push(`  { resourceType: '${resourceType}', parameterPath: '${parameterPath}', fetch: ${importName} },`)
}
lines.push(']')
lines.push('')

fs.writeFileSync(outputFile, lines.join('\n'), 'utf-8')

console.log(`Generated ${outputFile} with ${modules.length} completion module(s):`)
for (const { resourceType, parameterPath } of modules) {
  console.log(`  ${resourceType}${parameterPath}`)
}
